package ru.vdovin.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.vdovin.pft.addressbook.model.ContactData;

public class ContactDeletionTest extends TestBase {

    @Test
    public void testContactDeletion() {
        app.getNavigationHelper().gotoHomePage();
        if (! app.getContactHelper().isThereAnyContact()){
            app.getContactHelper().createContact(new ContactData("test",
                    "test",
                    "test",
                    "test",
                    "LFC",
                    "Moscow",
                    "test",
                    "+7-926-777-77-77",
                    "+7-495-777-77-77",
                    "test@test.ru",
                    "test@yandex.ru",
                    "test@gmail.ru",
                    "https://vk.com/",
                    null), false);
        }
        app.getNavigationHelper().gotoHomePage();
        app.getContactHelper().selectContact("selected[]");
        app.getContactHelper().deleteSelectedContact();
        app.getContactHelper().confirmDeletion();
        app.getNavigationHelper().gotoHomePage();
    }

}
