package ru.vdovin.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import ru.vdovin.pft.addressbook.model.ContactData;

import java.util.HashMap;
import java.util.Map;

public class ContactCreationTests {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost/addressbook/");
        login("admin", "secret");
    }

    private void login(String nickname, String password) {
        driver.manage().window().setSize(new Dimension(1552, 881));
        driver.findElement(By.name("user")).sendKeys(nickname);
        driver.findElement(By.name("pass")).sendKeys(password);
        driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void contactCreationTests() {
        initContactCreation();
        fillContactForm(new ContactData("Victor", "Vladimirovich", "Vdovin", "Voacka", "Afina LLC", "Moscow", "Zhuk", "+7-926-777-77-77", "+7-495-777-77-77", "vdovin@afina-pet.ru", "vdovin91@yandex.ru", "vdovin91@gmail.ru", "https://vk.com/id11120154"));
        returnToHomePage();
    }

    private void initContactCreation() {
        driver.findElement(By.linkText("add new")).click();
    }

    private void fillContactForm(ContactData contactData) {
        driver.findElement(By.name("firstname")).sendKeys(contactData.getFirstname());
        driver.findElement(By.name("middlename")).sendKeys(contactData.getMiddlename());
        driver.findElement(By.name("lastname")).sendKeys(contactData.getLastname());
        driver.findElement(By.name("nickname")).sendKeys(contactData.getNickname());
        driver.findElement(By.name("company")).sendKeys(contactData.getCompany());
        driver.findElement(By.name("address")).sendKeys(contactData.getAddress());
        driver.findElement(By.name("home")).sendKeys(contactData.getHome());
        driver.findElement(By.name("mobile")).sendKeys(contactData.getMobilePhone());
        driver.findElement(By.name("work")).sendKeys(contactData.getWorkPhone());
        driver.findElement(By.name("email")).sendKeys(contactData.getEmail1());
        driver.findElement(By.name("email2")).sendKeys(contactData.getEmail2());
        driver.findElement(By.name("email3")).sendKeys(contactData.getEmail3());
        driver.findElement(By.name("homepage")).sendKeys(contactData.getHomepage());
        driver.findElement(By.name("bday")).click();
        {
            WebElement dropdown = driver.findElement(By.name("bday"));
            dropdown.findElement(By.xpath("//option[. = '1']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.name("bmonth"));
            dropdown.findElement(By.xpath("//option[. = 'January']")).click();
        }
        driver.findElement(By.name("byear")).sendKeys("1991");
        {
            WebElement dropdown = driver.findElement(By.name("new_group"));
            dropdown.findElement(By.xpath("//option[. = '1']")).click();
        }
        driver.findElement(By.cssSelector("input:nth-child(87)")).click();
    }

    private void returnToHomePage() {
        driver.findElement(By.linkText("home page")).click();
    }

}
