package ru.vdovin.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.vdovin.pft.addressbook.model.ContactData;

public class ContactCreationTest extends TestBase {

    @Test
    public void testContactCreation() {
        app.getContactHelper().initContactCreation();
        app.getContactHelper().fillContactForm(new ContactData("test",
                "test",
                "test",
                "test",
                "LFC",
                "Moscow",
                "test",
                "+7-926-777-77-77",
                "+7-495-777-77-77",
                "test@test.ru",
                "test@yandex.ru",
                "test@gmail.ru",
                "https://vk.com/",
                null), true);
        app.getContactHelper().submitContactCreation();
        app.getNavigationHelper().gotoHomePage();
    }

}
