package ru.vdovin.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class ContactDeletionTest extends TestBase {

    @Test
    public void testContactDeletion() {
        app.getNavigationHelper().gotoHomePage();
        app.getContactHelper().selectContact("selected[]");
        app.getContactHelper().deleteSelectedContact();
        app.getContactHelper().confirmDeletion();
        app.getNavigationHelper().gotoHomePage();
    }

}
