package ru.vdovin.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTest extends TestBase {

    @Test
    public void testGroupDelete() {
        app.gotoGroupPage();
        app.selectGroup();
        app.deleteSelectedGroups();
        app.returnToGroupPage();
    }

}
