package ru.vdovin.pft.addressbook.tests; // Generated by Selenium IDE

import org.junit.Test;
import ru.vdovin.pft.addressbook.model.GroupData;

public class GroupCreationTest extends TestBase {

    @Test
    public void testGroupCreation() {
        app.getNavigationHelper().gotoGroupPage();
        app.getGroupHelper().createGroup(new GroupData("testnew", null, null));
    }

}
